language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-esri-widget' ]; then cd .. && eval "mv $currentfolder generator-esri-widget" && cd generator-esri-widget; fi

